# Generated by Django 2.1 on 2019-04-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='isdelete',
        ),
    ]
